FROM ghcr.io/actions/actions-runner:2.316.0 as base
# for latest release, see https://github.com/actions/runner/releases

USER root

# install curl and jq
RUN apt-get update && apt-get install -y curl jq && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY scripts/gha_entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]

FROM base as aca
# Required in ACA as sudoing is not possible
ENV RUNNER_ALLOW_RUNASROOT=true

FROM base as ecs

USER runner
