name: Publish Actions Runner image running as root

# TODO: Release job
on:
  push:
    branches: [aca_autoscaler]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: hi-fi/root-actions-runner

jobs:
  build-image:
    name: Publish image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: set lower case owner name
      run: |
        echo "IMAGE_NAME_LC=${IMAGE_NAME,,}" >>${GITHUB_ENV}
      env:
        OWNER: '${{ env.IMAGE_NAME }}'
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: images/
        file: images/Dockerfile.aca
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LC }}:latest
