name: Publish Actions Runner image running as root

# TODO: Release job
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: hi-fi/root-actions-runner

jobs:
  build-image:
    name: Publish image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Log in to the Container registry
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: set lower case owner name
      run: |
        echo "IMAGE_NAME_LC=${IMAGE_NAME,,}" >>${GITHUB_ENV}
      env:
        OWNER: '${{ env.IMAGE_NAME }}'
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 # v6.7.0
      with:
        context: .
        file: images/Dockerfile.aca
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LC }}:latest
