name: Image build test on ECS

on:
  workflow_dispatch:

jobs: 
  build:
    runs-on: ecs-runner-set
    steps:
      - run: echo "building"
      - run: |
          sudo apt update
          sudo apt install jq curl unzip -y
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws sts get-caller-identity
      - run: |
          echo "Executing Kaniko build"
          OUTPUT=$(aws ecs run-task --task-definition Kaniko --cluster $ECS_CLUSTER_NAME --network-configuration "awsvpcConfiguration={subnets=[$(aws ec2 describe-subnets --output text --query 'Subnets[*].SubnetId' | sed 's/\t/,/g')],securityGroups=[$(aws ec2 describe-security-groups --output text --query 'SecurityGroups[*].GroupId' | sed 's/\t/,/g')],assignPublicIp=ENABLED}" --launch-type FARGATE)
          echo $OUTPUT
          TASK_ARN=$(jq -r '.tasks[0].taskArn' <<< $OUTPUT)
          TASK_ID=${TASK_ARN##*/}
          echo "Waiting for task to complete"
          aws ecs wait tasks-stopped --cluster $ECS_CLUSTER_NAME --tasks $TASK_ARN
          aws logs get-log-events --log-group-name "/ecs/Kaniko" --log-stream-name "ecs/kaniko/$TASK_ID" --output text --query 'events[*].[timestamp,message]'
