name: Container step example
on: 
  workflow_dispatch:
    inputs:
      runner:
        desctiption: Runner to use
        required: true
        type: choice
        options:
          - ecs-runner-set
          - aca-runner-set
          - cr-runner-set

jobs:
  hello_world_job:
    runs-on: ${{ github.event.inputs.runner }}
    name: A job to say hello
    steps:
      - name: Run the Container Action
        id: run
        uses: actions/container-prebuilt-action@v0
        with:
          who-to-greet: Mona Lisa Octocat

      - name: Print Output
        id: output
        run: echo "${{ steps.run.outputs.greeting }}"
