name: Container step example
on: 
  workflow_dispatch:
    inputs:
      runner:
        desctiption: Runner to use
        required: true
        type: choice
        options:
          - ecs-runner-set
          - aca-runner-set
          - cr-runner-set
          - arc-runner-set

jobs:
  hello_world_job:
    runs-on: ${{ github.event.inputs.runner || 'aca-runner-set' }}
    name: A job to say hello
    steps:
      - name: Run the Container Action
        id: run
        uses: actions/container-prebuilt-action@v0
        with:
          who-to-greet: Mona Lisa Octocat

      - name: Print Output
        id: output
        run: echo "${{ steps.run.outputs.greeting }}"

      - name: Run the Container Action
        id: run2
        uses: actions/container-prebuilt-action@v0
        with:
          who-to-greet: Other greeted

      - name: Print Output
        id: output2
        run: echo "${{ steps.run2.outputs.greeting }}"
