name: Debug file system

# TODO: Release job
on:
  push:
    branches: [cloudrun]
  workflow_dispatch:
    inputs:
      runner:
        desctiption: Runner to use
        required: true
        type: choice
        options:
          - ecs-runner-set
          - aca-runner-set
          - cr-runner-set

jobs:
  files:
    name: Hello world
    runs-on: ${{ github.event.inputs.runner || 'cr-runner-set' }}
    steps:
      - name: List things
        run: |
          pwd
          ls -la /home/runner
          cd /home/runner/_work
          ls -la
          cd externals
          ls -la
      - name: Try to run node 16
        run: |
          cp /home/runner/_work/externals/node16/bin/node.bin /tmp/node
          chmod 777 /tmp/node
          ln -s /tmp/node /home/runner/_work/externals/node16/bin/node
          /home/runner/_work/externals/node16/bin/node -v
      - name: Try to run node 20
        run: |
          cp /home/runner/_work/externals/node20/bin/node.bin /tmp/node
          chmod 777 /tmp/node
          ln -s /tmp/node /home/runner/_work/externals/node20/bin/node
          /home/runner/_work/externals/node20/bin/node -v
      # - name: Copy externals
      #   if: always()
      #   run: cp -r /home/runner/externals/ /home/runner/_work/externals/
      # - name: Get checkout
      #   if: always()
      #   run: |
      #     sudo apt update
      #     sudo apt install wget -y
      #     wget https://github.com/actions/checkout/archive/refs/tags/v4.2.0.tar.gz
      #     cp v4.2.0.tar.gz /home/runner/_work/v4.2.0.tar.gz
      # - name: extract as is
      #   if: always()
      #   run: |
      #     cd /home/runner/_work
      #     tar xzvf v4.2.0.tar.gz
      #     ls -l /home/runner/_work/checkout-4.2.0
      #     rm -r checkout-4.2.0
      # - name: extract as is with root
      #   if: always()
      #   run: |
      #     cd /home/runner/_work
      #     sudo tar xzvf v4.2.0.tar.gz
      #     ls -l /home/runner/_work/checkout-4.2.0
      #     rm -r checkout-4.2.0
      # - name: extract with environment variables
      #   if: always()
      #   run: |
      #     echo $TAR_OPTIONS
      #     cd /home/runner/_work
      #     tar xzvf v4.2.0.tar.gz
      #     ls -l /home/runner/_work/checkout-4.2.0
      #   env:
      #     TAR_OPTIONS: --touch --no-overwrite-dir --no-same-owner
