name: Runner test
on: 
  workflow_dispatch:
    inputs:
      runner:
        description: Runner to use
        required: true
        type: choice
        options:
          - ecs-runner-set
          - aca-runner-set
          - cr-runner-set

# GITHUB_TOKEN doesn't need any permissions on this test workflow
permissions: {}

jobs:
  hello_world_job:
    runs-on: ${{ github.event.inputs.runner || 'local-arc' }}
    name: A job to say hello
    steps:
      - name: Print greetings for selected runner
        if: ${{ github.event.inputs.runner }}
        run: echo "Hello ${{ github.event.inputs.runner }}"

      - name: Print environment variables
        run: export
